version: '3'

# persist changes in your home directory
volumes:
  lcas_teaching_home:

services:
  bacchus_teaching:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    restart: "no"
    image: lcas.lincoln.ac.uk/lcas/lcas_teaching:teaching_humble
    environment:
      RESOLUTION: 1440x720
    volumes:
      - lcas_teaching_home:/home/ubuntu
      - .:/volume/host
      - /dev/net/tun:/dev/net/tun
    ports:
      - "7080:80"
      - "7081:8888"
      - "7082:22"
    cap_add:
      - NET_ADMIN
