name: 'devcontainer CI' 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 2324-devel
  push:
    branches:
      - 2324-devel

jobs:
  build:
    runs-on: lcas
    if: ${{ github.event_name != 'pull_request' }} 
    steps:
      - name: Node Js
        uses: actions/setup-node@v1
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: What
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Docker Login LCAS
        uses: docker/login-action@v3
        with:
          registry: lcas.lincoln.ac.uk
          username: ${{ secrets.LCAS_REGISTRY_PUSHER }}
          password: ${{ secrets.LCAS_REGISTRY_TOKEN }}
      - name: Docker Login dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: lcas.lincoln.ac.uk/lcas/devcontainer/ros2-teaching
          push: always
          imageTag: ${{ env.BRANCH }}